start implementing glib test using "array-test" as the starting point
move glib includes to a list and also use them in test

Currently getting the errors below, which is to be fixed in a follow up commit

```elvish
install
└─ run exe array-test
   └─ compile exe array-test Debug native 11 errors
error: ld.lld: undefined symbol: g_spawn_sync_impl
    note: referenced by gspawn.c:153 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gspawn.c:153)
    note:               .zig-cache/o/60a6bb42e74a14d87686652d2bfbdc09/gspawn.o:(g_spawn_sync) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: g_spawn_async_with_pipes_and_fds_impl
    note: referenced by gspawn.c:465 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gspawn.c:465)
    note:               .zig-cache/o/60a6bb42e74a14d87686652d2bfbdc09/gspawn.o:(g_spawn_async_with_pipes_and_fds) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: g_spawn_check_wait_status_impl
    note: referenced by gspawn.c:705 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gspawn.c:705)
    note:               .zig-cache/o/60a6bb42e74a14d87686652d2bfbdc09/gspawn.o:(g_spawn_check_wait_status) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: g_spawn_close_pid_impl
    note: referenced by gspawn.c:748 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gspawn.c:748)
    note:               .zig-cache/o/60a6bb42e74a14d87686652d2bfbdc09/gspawn.o:(g_spawn_close_pid) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: g_unix_open_pipe
    note: referenced by gwakeup.c:161 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gwakeup.c:161)
    note:               .zig-cache/o/f40baf99b0f771352cbfd92b9eb37495/gwakeup.o:(g_wakeup_new) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: g_unix_set_fd_nonblocking
    note: referenced by gwakeup.c:164 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gwakeup.c:164)
    note:               .zig-cache/o/f40baf99b0f771352cbfd92b9eb37495/gwakeup.o:(g_wakeup_new) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
    note: referenced by gwakeup.c:165 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gwakeup.c:165)
    note:               .zig-cache/o/f40baf99b0f771352cbfd92b9eb37495/gwakeup.o:(g_wakeup_new) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: _g_locale_get_charset_aliases
    note: referenced by gcharset.c:68 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gcharset.c:68)
    note:               .zig-cache/o/f4ceacf1ed7f4b4aca9a2854c12d4f92/gcharset.o:(get_alias_hash) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: _g_locale_charset_raw
    note: referenced by gcharset.c:215 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gcharset.c:215)
    note:               .zig-cache/o/f4ceacf1ed7f4b4aca9a2854c12d4f92/gcharset.o:(g_get_charset) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: _g_locale_charset_unalias
    note: referenced by gcharset.c:139 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gcharset.c:139)
    note:               .zig-cache/o/f4ceacf1ed7f4b4aca9a2854c12d4f92/gcharset.o:(g_utf8_get_charset_internal) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: _g_fd_is_journal
    note: referenced by gmessages.c:2161 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gmessages.c:2161)
    note:               .zig-cache/o/ee74abb82eefeff28817691c6f7ecdc9/gmessages.o:(g_log_writer_is_journald) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: ld.lld: undefined symbol: g_io_channel_unix_new
    note: referenced by gtestutils.c:3843 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gtestutils.c:3843)
    note:               .zig-cache/o/a5d46d8a361d0f78917121258822e894/gtestutils.o:(wait_for_child) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
    note: referenced by gtestutils.c:3854 (zig-pkg/N-V-__8AAKU0KQMunLzRshZbm1ufWgzgRURt7GbK_vUGaaEO/glib/gtestutils.c:3854)
    note:               .zig-cache/o/a5d46d8a361d0f78917121258822e894/gtestutils.o:(wait_for_child) in archive .zig-cache/o/59eca138c2b82cd1ae026ccc36c80858/libglib-2.0.a
error: 11 compilation errors
```

Signed-off-by: Bernard Assan <mega.alpha100@gmail.com>